from pathlib import Path

p = Path('src/renderer/src/App.tsx')
t = p.read_text(encoding='utf-8')

old = '''    async function createCategory() {\n        const name = window.prompt("Nome da nova aba da Biblioteca:")?.trim();\n        if (!name) return;\n        const created: LibraryCategory = {\n            id: `custom-${Date.now()}-${Math.random().toString(16).slice(2)}`,\n            name: name.slice(0, 40),\n            folderPath: "",\n            builtIn: false\n        };\n        const result = await window.santtosAPI.saveLibraryCategories([...categories, created]);\n        if (!result.ok) {\n            setCategoryStatus(result.error ?? "Não foi possível criar a aba.");\n            return;\n        }\n        const saved = result.categories ?? [...categories, created];\n        setCategories(saved);\n        setActiveCategoryId(created.id);\n        setCategoryStatus("Aba criada. Configure a pasta em Configurações → Biblioteca.");\n    }\n'''

new = '''    async function createCategory() {\n        const name = window.prompt("Nome da nova aba da Biblioteca:")?.trim();\n        if (!name) return;\n\n        setCategoryStatus("Selecione a pasta da nova aba...");\n\n        try {\n            const folderResult = await window.santtosAPI.selectLibraryFolder();\n\n            if (!folderResult.ok || !folderResult.folderPath) {\n                setCategoryStatus(\n                    folderResult.canceled\n                        ? "Criação cancelada: nenhuma pasta foi selecionada."\n                        : "Não foi possível selecionar a pasta da nova aba."\n                );\n                return;\n            }\n\n            const created: LibraryCategory = {\n                id: `custom-${Date.now()}-${Math.random().toString(16).slice(2)}`,\n                name: name.slice(0, 40),\n                folderPath: folderResult.folderPath,\n                builtIn: false\n            };\n\n            const result = await window.santtosAPI.saveLibraryCategories([\n                ...categories,\n                created\n            ]);\n\n            if (!result.ok) {\n                setCategoryStatus(\n                    result.error ?? "Não foi possível criar a aba."\n                );\n                return;\n            }\n\n            const saved = result.categories ?? [...categories, created];\n            setCategories(saved);\n            setActiveCategoryId(created.id);\n            setSearch("");\n            setCategoryStatus(`Aba ${created.name} criada e vinculada à pasta selecionada.`);\n\n            const scanResult = await window.santtosAPI.scanLibraryCategory(created.id);\n            if (scanResult.ok && (scanResult.filePaths?.length ?? 0) > 0) {\n                await onImportDroppedFiles(scanResult.filePaths ?? []);\n                setCategoryStatus(\n                    `Aba ${created.name} criada. ${scanResult.filePaths?.length ?? 0} arquivo(s) encontrado(s).`\n                );\n            }\n        } catch (error) {\n            console.error(error);\n            setCategoryStatus("Não foi possível criar a nova aba da Biblioteca.");\n        }\n    }\n'''

if old not in t:
    raise SystemExit('createCategory anchor not found')

t = t.replace(old, new, 1)
p.write_text(t, encoding='utf-8')
print('New library tab now requires folder selection and scans immediately')
