from pathlib import Path

p=Path('src/renderer/src/App.tsx')
t=p.read_text(encoding='utf-8')

def r(old,new,label):
    global t
    if old not in t:
        raise SystemExit(f'anchor missing: {label}')
    t=t.replace(old,new,1)

r('''            importMedia: (\n                filePaths: string[]\n            ) => Promise<ImportResult>;''','''            importMedia: (\n                filePaths: string[]\n            ) => Promise<ImportResult>;\n            getDroppedFilePath: (file: File) => string;''','api type')

r('''    async function handleRemoveMedia(\n        mediaItem: MediaItem\n    ) {''','''    async function importDroppedFiles(\n        filePaths: string[]\n    ): Promise<ImportResult> {\n        if (filePaths.length === 0) {\n            return {\n                importedItems: [],\n                duplicatedItems: [],\n                media\n            };\n        }\n\n        setIsLoading(true);\n        setMessage(\"\");\n        try {\n            const result =\n                await window.santtosAPI.importMedia(filePaths);\n            setMedia(result.media);\n\n            if (result.importedItems.length > 0) {\n                setMessage(\n                    `${result.importedItems.length} vídeo(s) importado(s) por arrastar e soltar.`\n                );\n            } else if (result.duplicatedItems.length > 0) {\n                setMessage(\n                    \"A mídia arrastada já estava cadastrada.\"\n                );\n            }\n\n            return result;\n        } finally {\n            setIsLoading(false);\n        }\n    }\n\n    async function handleRemoveMedia(\n        mediaItem: MediaItem\n    ) {''','parent import function')

r('''                            onAddVideos={addVideos}\n                            onRemoveMedia={handleRemoveMedia}''','''                            onAddVideos={addVideos}\n                            onImportDroppedFiles={importDroppedFiles}\n                            onRemoveMedia={handleRemoveMedia}''','pass prop')

r('''    onAddVideos: () => Promise<void>;\n    onRemoveMedia: (''','''    onAddVideos: () => Promise<void>;\n    onImportDroppedFiles: (\n        filePaths: string[]\n    ) => Promise<ImportResult>;\n    onRemoveMedia: (''','playout prop type')

r('''    onSelectMedia,\n    onAddVideos,\n    onRemoveMedia''','''    onSelectMedia,\n    onAddVideos,\n    onImportDroppedFiles,\n    onRemoveMedia''','playout destructure')

# Add handlers before return
r('''    function moveTimelineItem(targetMediaId: string) {''','''    async function importExplorerFilesToTimeline(\n        files: FileList,\n        targetMediaId?: string\n    ) {\n        const paths = Array.from(files)\n            .map((file) =>\n                window.santtosAPI.getDroppedFilePath(file)\n            )\n            .filter((value): value is string => Boolean(value));\n\n        if (paths.length === 0) {\n            return;\n        }\n\n        try {\n            const result = await onImportDroppedFiles(paths);\n            const normalized = (value: string) =>\n                value.replace(/\\\\/g, \"/\").toLowerCase();\n            const wanted = new Set(paths.map(normalized));\n            const items = result.media.filter((item) =>\n                wanted.has(normalized(item.path))\n            );\n\n            items.forEach((item, index) => {\n                addTimelineItem(\n                    item,\n                    index === 0 ? targetMediaId : undefined\n                );\n            });\n        } catch (error) {\n            console.error(\n                \"Erro ao importar arquivos do Explorer para a timeline:\",\n                error\n            );\n        }\n    }\n\n    function moveTimelineItem(targetMediaId: string) {''','timeline external handler')

# Timeline panel dragover/drop
old='''                    onDragOver={(event) => {\n                        if (\n                            event.dataTransfer.types.includes(\n                                \"application/x-santtos-library-media\"\n                            )\n                        ) {\n                            event.preventDefault();\n                            event.dataTransfer.dropEffect =\n                                \"copy\";\n                        }\n                    }}\n                    onDrop={(event) => {\n                        const mediaId =\n                            event.dataTransfer.getData(\n                                \"application/x-santtos-library-media\"\n                            );\n\n                        if (!mediaId) {\n                            return;\n                        }\n\n                        event.preventDefault();\n                        const item = media.find(\n                            (entry) =>\n                                entry.id === mediaId\n                        );\n\n                        if (item) {\n                            addTimelineItem(item);\n                        }\n                    }}'''
new='''                    onDragOver={(event) => {\n                        const hasFiles =\n                            event.dataTransfer.types.includes(\"Files\");\n                        const hasLibraryMedia =\n                            event.dataTransfer.types.includes(\n                                \"application/x-santtos-library-media\"\n                            );\n\n                        if (hasFiles || hasLibraryMedia) {\n                            event.preventDefault();\n                            event.dataTransfer.dropEffect = \"copy\";\n                        }\n                    }}\n                    onDrop={(event) => {\n                        if (event.dataTransfer.files.length > 0) {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            void importExplorerFilesToTimeline(\n                                event.dataTransfer.files\n                            );\n                            return;\n                        }\n\n                        const mediaId =\n                            event.dataTransfer.getData(\n                                \"application/x-santtos-library-media\"\n                            );\n\n                        if (!mediaId) {\n                            return;\n                        }\n\n                        event.preventDefault();\n                        const item = media.find(\n                            (entry) => entry.id === mediaId\n                        );\n\n                        if (item) {\n                            addTimelineItem(item);\n                        }\n                    }}'''
r(old,new,'timeline panel dnd')

# Timeline item dragover/drop external files
r('''                                                const isLibraryMedia =\n                                                    event.dataTransfer.types.includes(\n                                                        \"application/x-santtos-library-media\"\n                                                    );\n\n                                                if (\n                                                    isLibraryMedia ||\n                                                    !isCurrent\n                                                ) {''','''                                                const isLibraryMedia =\n                                                    event.dataTransfer.types.includes(\n                                                        \"application/x-santtos-library-media\"\n                                                    );\n                                                const hasFiles =\n                                                    event.dataTransfer.types.includes(\"Files\");\n\n                                                if (\n                                                    hasFiles ||\n                                                    isLibraryMedia ||\n                                                    !isCurrent\n                                                ) {''','item dragover')

r('''                                                const libraryId =\n                                                    event.dataTransfer.getData(\n                                                        \"application/x-santtos-library-media\"\n                                                    );\n\n                                                if (libraryId) {''','''                                                if (event.dataTransfer.files.length > 0) {\n                                                    void importExplorerFilesToTimeline(\n                                                        event.dataTransfer.files,\n                                                        item.id\n                                                    );\n                                                    return;\n                                                }\n\n                                                const libraryId =\n                                                    event.dataTransfer.getData(\n                                                        \"application/x-santtos-library-media\"\n                                                    );\n\n                                                if (libraryId) {''','item drop files')

# Pass import callback to Library
r('''                    onAddVideos={onAddVideos}\n                    onRemoveMedia={onRemoveMedia}''','''                    onAddVideos={onAddVideos}\n                    onImportDroppedFiles={onImportDroppedFiles}\n                    onRemoveMedia={onRemoveMedia}''','library prop pass')

# Library props
r('''    onAddVideos: () => Promise<void>;\n    onRemoveMedia: (\n        media: MediaItem''','''    onAddVideos: () => Promise<void>;\n    onImportDroppedFiles: (\n        filePaths: string[]\n    ) => Promise<ImportResult>;\n    onRemoveMedia: (\n        media: MediaItem''','library prop type')

r('''    message,\n    onAddVideos,\n    onRemoveMedia,''','''    message,\n    onAddVideos,\n    onImportDroppedFiles,\n    onRemoveMedia,''','library destructure')

# Library section handlers
r('''    return (\n        <section className=\"panel module-panel\">''','''    async function handleExplorerDrop(\n        files: FileList\n    ) {\n        const paths = Array.from(files)\n            .map((file) =>\n                window.santtosAPI.getDroppedFilePath(file)\n            )\n            .filter((value): value is string => Boolean(value));\n\n        if (paths.length > 0) {\n            await onImportDroppedFiles(paths);\n        }\n    }\n\n    return (\n        <section\n            className=\"panel module-panel\"\n            onDragOver={(event) => {\n                if (event.dataTransfer.types.includes(\"Files\")) {\n                    event.preventDefault();\n                    event.dataTransfer.dropEffect = \"copy\";\n                }\n            }}\n            onDrop={(event) => {\n                if (event.dataTransfer.files.length === 0) {\n                    return;\n                }\n                event.preventDefault();\n                event.stopPropagation();\n                void handleExplorerDrop(event.dataTransfer.files);\n            }}\n        >''','library section external dnd')

p.write_text(t,encoding='utf-8')
print('Explorer drag drop patch applied')
